# License: LGPL-2.1
#

name: apts

on:
  workflow_dispatch:
#  push:
#    branches: ["act"]

jobs:
  apt-1:
    runs-on: ubuntu-26.04

    steps:
    - name: Start
      run: |
        echo nproc: $(nproc)
        cat /etc/apt/apt-mirrors.txt

    - name: Apt Set
      run: |

        # echo 'APT::Default-Release "resolute";' | sudo tee /etc/apt/apt.conf.d/Default-Release

        echo "deb http://archive.ubuntu.com/ubuntu stonking main restricted universe multiverse"   | sudo tee /etc/apt/sources.list.d/plus.list
        echo "deb http://ftp.debian.org/debian sid main contrib non-free"                       | sudo tee -a /etc/apt/sources.list.d/plus.list
        # echo "deb http://ftp.debian.org/debian experimental main contrib non-free"              | sudo tee -a /etc/apt/sources.list.d/plus.list

        cat <<EOF | sudo tee /etc/apt/preferences.d/plus-pin

        Package: *
        Pin: release n=stonking
        Pin-Priority: 850

        Package: *
        Pin: release n=resolute
        Pin-Priority: 800

        Package: *
        Pin: release n=sid
        Pin-Priority: 750

        Package: *
        Pin: release a=experimental
        Pin-Priority: 400

        EOF

        wget -O- 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x78DBA3BC47EF2265' \
          | sudo tee /etc/apt/trusted.gpg.d/78DBA3BC47EF2265-Debian-13-trixie.asc > /dev/null

    - name: Apt Update
      run: |
        sudo apt-get update

    - name: Apt-Cache Policy
      run: |
        #apt-cache policy libc6 ccache cmake mesa-vulkan-drivers libicu-dev libicu78 libeigen3-dev libgdal-dev wget vtk9-dev libfmt-dev squashfs-tools
        apt-cache policy ccache cmake libeigen3-dev libfmt-dev vtk9 libvtk9-dev

    - name: Apt Install
      run: |
        sudo apt-get install -V \
          ccache                        \
          gcc-15  g++-15  gfortran-15   \
          binutils                      \
          libicu-dev                    \
          libfmt-dev                    \
          libpyside6-dev                \
          libshiboken6-dev              \
          qt6-tools-dev                 \
          qt6-svg-dev                   \
          python3-pyside6.qtwidgets     \
          python3-pyside6.qtsvgwidgets  \
          python3-pyside6.qtnetwork     \
          python3-pybind11              \
          libyaml-cpp-dev               \
          libxerces-c-dev               \
          libboost-filesystem-dev       \
          libboost-regex-dev            \
          libboost-program-options-dev  \
          libboost-thread-dev           \
          libmedc-dev                   \
          python3-lark                  \
          libfreeimage-dev              \
          libfreetype-dev               \
          libharfbuzz-dev               \
          libgtest-dev  libgmock-dev    \
          squashfs-tools                \
          swig  rdiff  xxhash

    - name: Apt Install /Sid
      run: |
        sudo apt-get install -V -t=sid --allow-downgrades \
          libvtk9-dev


